### ISSUE TITLE
Ripp offs....

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#107]
I can't help but to smile when I see the audacity from this guy,

First he take this whole repo,  creates his own repo over at Gitlab.
Then promptly changes text to indicate he is the one developing it.  

One of the last commits,  that it should go fund him for development.  

https://gitlab.com/Gtpy/ChameleonMini-RevG_GUI/commit/e5823b11d492d17518c198f151c71d796adc4ecf

**Comment by cjbrigato** [comment]
It is 404ed for me. I hoping for some cache to never forget

**Comment by cjbrigato** [comment]
Whole account 404ed

**Comment by iceman1001** [comment]
wut,  it disappeared..
