### ISSUE TITLE
[REQ] Option to uploads to all slots the same dump

### ISSUE THREAD

**Issue by BreakSecurity** [iceman1001/ChameleonMini-rebootedGUI#119]
Would be nice to have the possibility to uploads to all slots the same dump. It could be useful in field testing when I have to guess what the reader is doing to the tag. 

E.g. I have some checksum computed on the base of some tag information and timestamp, to reverse the operations done by the reader could be useful to use the same dump in different times.

**Comment by BreakSecurity** [comment]
Selected slot from 4 to 8 and tried to upload an MFU dump GUI freeze as in #117 and only the last slot was effectively written

**Comment by grspy** [comment]
Every time I tried with a .bin dump, it worked fine. Are you still trying to mass upload that json file? Can you please convert it first to .bin using the file manager (Utils tab) and try with that?

**Comment by BreakSecurity** [comment]
Same problem with the .bin file attached

[test.zip](https://github.com/iceman1001/ChameleonMini-rebootedGUI/files/3961136/test.zip)
