### ISSUE TITLE
v1.0.0 GUI - click once deployment

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#13]
There were some talk about binary releases or distro for those who can't compile the source for the GUI.
I did a click-once deployment, where it downloads and installed it from the link below.

It also checks for updates,  so yes, it calls home,  read on click-once what it means,  its the Microsoft built-in option.  If update is found, it updates the software and restarts it.   

Go ahead and test it out!

REF:
http://www.icesql.se/download/ChameleonMiniGUI/publish.htm

**Comment by kevin2008-01** [comment]
unable to connect with chameleon.
(stock firmware 1.0)

**Comment by iceman1001** [comment]
Do you have other usb-devices connected?   The com-port selection could be buggy

**Comment by iceman1001** [comment]
pushed some changes,  close the gui and restart it,  that will trigger the update

**Comment by kevin2008-01** [comment]
1 - install GUI, exit Gui, restart GUI.
2 - unable to connect to the chameleon.
(stock firmware new 1.0) (com8) (disable signed driver) (win 8.1 - 64)
3 - Driver is correctly installed and no problem.
4 - start original GUI and working.

**Comment by iceman1001** [comment]
Uninstall?   It should be the normal way of un-installning a software in Windows,  nothing out-of-norm there.
Which device are you using,  revE rebooted or revG?  
And do you have more devices connected ?

**Comment by kevin2008-01** [comment]
1 - i use setup.exe and accept many warning, and many authorization.
2 - when i launch GUI connect to your server, it's ok.
3 - When i click connect, i have this message (unable to connect to the chameleon).
4- I have revE rebooted with original firmware (original firmware: version: new chameleon 1.0).
5 - No more device attached, only rebooted on com8 or com3.
6 - Rebooted work fine with original sotware, and no problem with the driver.
7 - When i use the rebooted, i boot windows 8.1 with unsigned driver permission.

I'm not sure, but the GUI can't detect rebooted.

**Comment by kevin2008-01** [comment]
1 - GUI can't detect, and connect error when i click connect. Disconnect is black.
2 - Changing port is my first action. (driver attribute com8, i change with com3), com5 is occupied by pm3 driver.

**Comment by iceman1001** [comment]
This is strange.  I use rebooted device,  with original firmware and it finds the device. 

The application needs to download some dependencies to your computer like dot.net v4.5.2

**Comment by kevin2008-01** [comment]
i see, but Framework 4.5.2 or higher is installed on you computer

**Comment by kevin2008-01** [comment]
now i update the gui, and no working

**Comment by kevin2008-01** [comment]
question: the driver is LUFA-CDC ... ?

**Comment by iceman1001** [comment]
LUFA-CDC == normal mode ,  yes

**Comment by kevin2008-01** [comment]
i have this

**Comment by bogiton** [comment]
@kevin2008-01 Can you please check what name does the device has in the device manager? It should be listed under the "Ports (COM & LPT)".

**Comment by kevin2008-01** [comment]
![capture](https://user-images.githubusercontent.com/34159692/35240211-05a9431c-ffb3-11e7-9a14-f25862c318ae.JPG)
#
![capture2](https://user-images.githubusercontent.com/34159692/35240226-10f24a8e-ffb3-11e7-9857-630635e10bda.JPG)
![capture3](https://user-images.githubusercontent.com/34159692/35240231-15beeeaa-ffb3-11e7-9e2d-d43500adda37.JPG)
![capture4](https://user-images.githubusercontent.com/34159692/35240240-19be3fb0-ffb3-11e7-9943-f1a2b7eee9be.JPG)

**Comment by iceman1001** [comment]
yup.  Its the wmi selection that fails.   @bogiton  is doing a fix for it. :)

**Comment by kevin2008-01** [comment]
![capture5](https://user-images.githubusercontent.com/34159692/35240355-6ff2786a-ffb3-11e7-9385-ad93213f088a.JPG)

**Comment by iceman1001** [comment]
ok.  restart the client, I've deployed a new version

**Comment by kevin2008-01** [comment]
Goooalllllllll ++++++++

**Comment by kevin2008-01** [comment]
![capture6](https://user-images.githubusercontent.com/34159692/35242514-1028448a-ffba-11e7-8264-d4647682df5d.JPG)

**Comment by iceman1001** [comment]
Restart once more and the text looks better. 

I suppose this means v1.0 release is due

**Comment by kevin2008-01** [comment]
oh very good !!!
Please don't loose sak return (-.-) fonction.
V1.0 béta is valided....
Thank you @iceman1001 @bogiton

**Comment by iceman1001** [comment]
I updated the readme.md file,   this issue will be closed.
