### ISSUE TITLE
How to GETUID

### ISSUE THREAD

**Issue by Bowski1981** [iceman1001/ChameleonMini-rebootedGUI#137]
Hi All,

I am using the Chameleon Tiny for a few days and I am not used to it yet.
I managed to use some basic functions and get the connection to my Mac working properly.

There is something I am just wondering about... When reading an UID by GETUID and copying this to another slot, the UID changes. So the UID which is shown in my Tiny is different from the one I am reading from the card directly. Even when using the clone command it differs from the original UID every time.

Am I missing something? Or is it just normal?

**Comment by iceman1001** [comment]
Start with post all different steps you did,  otherwise noone can follow your issue.

And don't randomly label issues. We, the maintainers,  do the labeling.

**Comment by Bowski81** [comment]
Thanks a lot for your answer and sorry for any inconveniences caused.

I followed the first step guide on GitHub to setup my chameleon tiny.

It is working properly and I am able to read several tags and get the correct UID.

However, while trying to simulate an ISO14443 Tag and setting the UID it won't let me change the UID.

Here is a screenshot of the problem:
<img width="579" alt="Bildschirmfoto 2020-04-15 um 22 27 27" src="https://user-images.githubusercontent.com/62775663/79385263-91f06a80-7f68-11ea-87a3-6e165d2c1cef.png">

As you can see I'm trying to change the UID. But it does change the UID every time. I am not able to change it to the value I want.

Am I missing something?

**Comment by iceman1001** [comment]
Chameleon Tiny is a RevG based device.  This is the GUI project,   in what why does the GUI not work for you?  Otherwise you should direct your question to the Rfidresearchgroups' firmware repo for RevG / Tiny,   ref:   https://github.com/RfidResearchGroup/ChameleonMini
