### ISSUE TITLE
HELP text truncated

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#139]
**Describe the bug**
The output from the HELP command inside tab serial,  should print all available commands.

**To Reproduce**
1. Go to TAB SERIAL
2. Click on HELP
3. Client on SEND
4. See error at the end of the output from that command.

**Expected behavior**
To list the same amount of detected available commands as to list to the left on tab serial.

**Screenshots**
![image](https://user-images.githubusercontent.com/8577004/82430416-93dcaa80-9a8d-11ea-8ade-901cdf0154a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Loupetre** [comment]
Hello,

At the line 1798 of the FrmMain.cs file, just change 
int blockLimit = 275;
by
int blockLimit = 375;

The typical answer's lenght of the HELP commande is 347 bytes.

Here is the result after changing this value :

![image](https://user-images.githubusercontent.com/62932842/100266292-dfe33d00-2f51-11eb-9610-db5928079c78.png)

**Comment by iceman1001** [comment]
Great catch!
Make a PR?

**Comment by Loupetre** [comment]
Sorry, I see you've made the change before I succeeded in understanding what is a PR and how to do it : I've never made anything like that :)
I gonna go for a try with another small enhancement (french language, that is my cup of tea).
