### ISSUE TITLE
Giant text on high-resolution display makes Slot Configuration unreadable

### ISSUE THREAD

**Issue by bmorgenthaler** [iceman1001/ChameleonMini-rebootedGUI#140]
The text size does not appear to adjust with display settings and defaults to a giant size making all the slot configuration information unreadable.

1. Open application on high resolution (3440x1440 or higher) desktop

**Expected behavior**
Text resizes with OS settings for Ease of Access, Font Scaling, etc. and is not cut off.

**Screenshots**
![Screen Shot 2020-06-30 at 10 04 26 AM](https://user-images.githubusercontent.com/840560/86143158-b533ac00-bab9-11ea-9a09-ed8814539e10.png)

**Desktop**
 - OS: Windows 10 Parallels VM on MacOS 10.15.5

**Comment by bmorgenthaler** [comment]
Nevermind, magically fixed itself.

**Comment by iceman1001** [comment]
The gui doesn't enforce any font sizes.  It should adapt to Windows settings.
