### ISSUE TITLE
setup error?!?

### ISSUE THREAD

**Issue by AndreasBujok** [iceman1001/ChameleonMini-rebootedGUI#16]
Hi

i've allready installed the "Microsoft.NET Framework 4.5.2" (.NET Framework 4.5.2 or a later update is already installed on this computer.
) and on start of "ChameleonMiniGUI.application", he will connect anyway to the internet.

Is this the corect behavior?

BR Andreas

**Comment by bogiton** [comment]
Hi there. Yes, it checks for updates when starting.

**Comment by iceman1001** [comment]
https://github.com/iceman1001/ChameleonMini-rebootedGUI/issues/13

**Comment by AndreasBujok** [comment]
@bogiton 
Thanks for the info but means, i can't run offline?

**Comment by iceman1001** [comment]
you should be able to cancel the update request...
