### ISSUE TITLE
multi language support

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#18]
Adding multilanguage support. 
I think that textfiles with different languages will be fine.
and a dropdown to select language.
also adding saving the prefered language in the config file.

**Comment by iceman1001** [comment]
@bogiton    I just added the multilanguage support.
Would you mind testing it out.   I know the hexbox isn't translated since I only extracted control.Text values into the language files

**Comment by bogiton** [comment]
Ha! This is very cool! Never tried the multilingual capabilities of .NET before. There are some strings missing from the translation file, as you said, but it works perfectly nonetheless! Good job! :)

**Comment by iceman1001** [comment]
its actually not the builtin globalization support in dot.net.   That involves  compiled localized dlls which can't be edited later on. 

Its my own take on it.  With simple text files. 

I asked for a Chinese translation.  Dunno if you want to add a greek one ;)
