### ISSUE TITLE
GUI draft for release v1.1 

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#26]
@bogiton   I started with a draft,  feels like this current status is good enough for a new release.
Would you mind read and adapt it?

**Comment by bogiton** [comment]
I did edit it a bit. I will also try to re-arrange the settings tab today, as we discussed. Maybe we should change the recognition of the devices based on the PID&VID? After these, I believe we will have a nice new release.

**Comment by iceman1001** [comment]
And we are going to start with making a branch for each release.

**Comment by iceman1001** [comment]
So,  I tried to add the VID/PID for RevG.   The picture was wrong when no device was detected.
Not sure if its the right VID/PID.   And someone said RevG not working on the GUI..

1. waiting for chinese languatranslation

What more would we need???

**Comment by bogiton** [comment]
The VID/PID for RevG seems correct. I double-checked it in other repos. But the string to compare it with needs to be like this: "VID_16D0&PID_04B2".
I will provide a greek translation too, but some controls need to be resized a bit to fit the translated text. So, I will also do that later tonight.
After that: Happy new release! :)

**Comment by iceman1001** [comment]
I dunno if anyone besides English and Chinese will need a translation.

**Comment by iceman1001** [comment]
So this release will also get templates for Memory dumps  :)

**Comment by iceman1001** [comment]
Got the chinese translation. 

Time for release  @bogiton ?

**Comment by bogiton** [comment]
Almost there! I'm doing some minor resizing again to fit all the translations. Will PR shortly.

**Comment by iceman1001** [comment]
:)
Some mistake,   the **open location** button is not supposed to open languages folder.
I just put it in the languages groupbox,  since it didn't it in otherwere.

I suggest we change the groupbox name for it to be  Languages & Templates

**Comment by bogiton** [comment]
Ah, ok, sorry. Yeah, I thought it was meant to open only the languages folder. Yeah, we should rename the groupbox to "Languages & Templates", as you suggest.

**Comment by iceman1001** [comment]
no worries,  it was I, who was unclear.

**Comment by bogiton** [comment]
Should I close the PR, make the changes and do a new one?

**Comment by iceman1001** [comment]
do what will be easiest for you.

**Comment by bogiton** [comment]
I did the changes and the PR was updated automatically! Magic!
Should be ok to merge now.

**Comment by iceman1001** [comment]
well,  we got franch translation and I'm expecting a italian soon.  Also the serial tab is there,  might wait with the release until its finished.

**Comment by kevin2008-01** [comment]
iceman don't loose +1 / -1 increment. thank

**Comment by iceman1001** [comment]
+1 / -1 ??  in the GUI?   I'm not following,  please explain.

**Comment by kevin2008-01** [comment]
all is ok in last update. left and right increment...

**Comment by iceman1001** [comment]
I don't think RevE firmware has increament.   
if you use a RevG ,  those inc - modes should show up,  since we query the device which supported modes it has.

**Comment by kevin2008-01** [comment]
serial interface working ? actually not for me rev e rebooted.

**Comment by iceman1001** [comment]
How does it look when you send?

I just pushed a fix for the send button, which didn't send anything.
Now you can send via button,  or  with pressing enter

**Comment by iceman1001** [comment]
The serial interface tab is really not for amateurs.  
The GUI itself also assumes people know of what a chameleon can do or does.

**Comment by iceman1001** [comment]
With translations, color legend, dump management, serial interface,  I think its ready for a release.

Some questions asked in other threads by @kevin2008-01 
a) tab serial, add "?" to help text
b) tab operations,    +1 / -1 increment uid 

When it comes to a),   its not useful since the full commands uses  ? for query,  = for set, 
when it comes to b) ,  I think inc/dec uid is a firmware mode issue,  not a GUI issue.

**Comment by kevin2008-01** [comment]
right. wooo

(a)For "?" is just in serial interface, in description command add "versionmy?" at "versionmy", and many command, it's simply for copy paste for newbies. Yes for"?", if not, command not working.
I explain, in command description, i see "command versionmy"  when i send command i write "versionmy?" for working, if no "?", no working, understand me?

(b) +1 and -1 is left and right increment or decrement, but it's implemented at last version. but i'have E rev, and is instead, but not tested yet.

(c) in upgrade firmware, please, precise, upgrade with iceman firmware directly for newsbees. 

For sak 08/88, i have time, i explain to you in future.

Thank's and see you.

**Comment by kevin2008-01** [comment]
now i see.
good job. the result is perfect.

**Comment by iceman1001** [comment]
A) Ii don't target newbies with this GUI.  its for medium/experienced users.   If you don't understand the commandset nor read the differences of revE / revG firmware you should not use the serial interface.  I don't even want to use it.  Its usage makes even the pm3 client look easy.
For newbies you have the  Tab  Operations in order to use the chameleon.

B) if the inc/dec  modes are active inside firmware,  they should show in the dropdowns on  tab Operations.

C) sak/atqa needs firmware change,  until then there is no reason to change GUI.

--- All questions solved.
its time for a release.  @bogiton  do you want to change something in the description of the release?
B)

**Comment by bogiton** [comment]
I did edit it a little bit. I believe we are ready to rock :)

**Comment by iceman1001** [comment]
And now I got the italian translation from @asper   (thanks bro!)   
Its ready to be released

**Comment by iceman1001** [comment]
Its a release!
Thank you to all contributors!   (@bogiton , @kevin2008-01  @asper  @proxgrind)  
We made a good run this time.

**Comment by kevin2008-01** [comment]
if, you need translator for pm4, i'm here... I'm, in the road for july.... congratulations.....
