### ISSUE TITLE
GUI - tab for serial interface

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#30]
Suggestion,  I saw @WolfgangMau GUI has a serial interface which is a great idea.

GUI,
 - Tab for serial interface.

**Comment by bogiton** [comment]
I would love a serial interface!

**Comment by iceman1001** [comment]
I can start it after we merge your PR..

**Comment by iceman1001** [comment]
@bogiton   I have added a Serial - tab.   Tell me what you think

**Comment by bogiton** [comment]
I works perfectly! Good job man!

The only suggestions I have are the following:
- Add also a "Send" button for the sending of the commands
- Clear the command-send textbox after sending
- Get the available commands for each Chameleon version by sending HELP/HELPMY on connect

Again, great addition! :)

**Comment by iceman1001** [comment]
...now, why didn't I think on getting the available commands via the help?  That is a spendid idea.

**Comment by iceman1001** [comment]
@bogiton   
I adapted the following fixes,   
- clear button also empty the commandtext.
- help texts now loaded from firmware command and is selectable.

**Comment by iceman1001** [comment]
and a send button.  
time to close
