### ISSUE TITLE
update translation files.

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#34]
The following language files needs to be updated:
- Chinese

**Comment by kevin2008-01** [comment]
french updated. see you.

**Comment by iceman1001** [comment]
merci! 
its it "Bits" in french?!?   8bits == 1byte in english

**Comment by kevin2008-01** [comment]
Hummm, confusion for newbies. Change to original byte

**Comment by bogiton** [comment]
Done! :)

**Comment by iceman1001** [comment]
nice
Is the command called button_long or?

**Comment by bogiton** [comment]
Yes, both in our firmware and in RevG's. We had that as BUTTONLONG in the GUI, so I changed it to be consistent with the firmwares.
