### ISSUE TITLE
eml format upload directecly 

### ISSUE THREAD

**Issue by kevin2008-01** [iceman1001/ChameleonMini-rebootedGUI#39]
eml format upload dump directecly,  is possible in future ?

see you

**Comment by iceman1001** [comment]
the concepts of eml file is counter to what a hex-edit does.
you should be able to just drop and drag a eml file already, but you will see why its not fitted for a hexeditor.

How about some converters?  That would be nice,  
EML -> BIN  
BIN -> EML

**Comment by kevin2008-01** [comment]
Yep, converter is fine...

**Comment by iceman1001** [comment]
@bogiton   What do you think of this style for converting?

![image](https://user-images.githubusercontent.com/8577004/40055944-0a5cd2a8-584a-11e8-8acb-548f2bc77b34.png)

**Comment by bogiton** [comment]
Hmm, I was thinking something like auto-converting when uploading to a slot or when loading a dump for hex editing. But if we are gonna implement a file manager we could add more features to the context menu, like add to hexeditorX or even load directly to slotX.
Another option could be a "Converter" button in the dump management tab (since converting seems like a part of that) that displays a dialog to select the files to convert from/to and the type of the conversion to perform.

**Comment by iceman1001** [comment]
hehe,  I wanted first just a list of files with a checkbox  and try to work in batches..
but then I realised the dump files will be anywhere on the computer drives.
Also thought of button, but samething there, I might not want to convert the file I'm watching.

With a simpler filemanager,  we can add more possibilities like you say with "compare 1" / "compare 2"..
and yes,  upload to slot,   and we don't have to have all files in one place etc..

**Comment by iceman1001** [comment]
In my first try I called the tab "Convert"..  I realised "Utils" would be better.

**Comment by bogiton** [comment]
Yeah, let's go with the file manager then and we can add the other goodies there :)

**Comment by iceman1001** [comment]
ok,  I pushed the code so far.  Missing some nice folder icons etc..  and layout etc..  but it can convert :)

**Comment by bogiton** [comment]
You are damn fast! You even created your own file manager control?? We could have used a free one :P
Btw, I'm getting some build errors, about the following missing files:
Error: Could not find file 'Templates\LegoDimension.txt'
Error: Could not find file 'Templates\Ultralight-EV1-48b.txt'
Error: Could not find file 'Templates\VingCard EV1-48b  (pm3).txt'

**Comment by iceman1001** [comment]
aha,  I see,  they can be excluded from project.  I pushed a fix for it.

Well,  c# is easy sometimes.  No need to over-do things.  There are blogs on internet to follow.  :) 
Now we need some image icons,  like folder,  locked-folder,  file,  drive.   four of them I think.

**Comment by iceman1001** [comment]
I didn't want to make a full fledge file explorer, just something that fits our needs to work better.

**Comment by iceman1001** [comment]
the icons should be added to the imagelist control..

**Comment by hiwanz** [comment]
@iceman1001 It's better to create a project with this repo, so that contributors can follow the progress and do what they can do for the repo.

![image](https://user-images.githubusercontent.com/338102/45583877-632d9080-b8fc-11e8-9bc9-85c4f4988596.png)

**Comment by iceman1001** [comment]
@hiwanz   not the best place to chat about project.   I have however enabled it now.

**Comment by hiwanz** [comment]
project is not for discussing things but planning them

**Comment by hiwanz** [comment]
for example, you can add todos to the list, something like 

- [ ] Add "Send to hexbox" menu item to the context menu
- [ ] Need more templates
- [ ] "To MFD" need to be done
...

so that contributors can pick up what they can do to help

**Comment by iceman1001** [comment]
This issue is not for discuss project.  This issue is about EML converting.  Keep issues clean and to the point.  
Start a new issue instead.

**Comment by iceman1001** [comment]
https://github.com/iceman1001/ChameleonMini-rebootedGUI/projects/1

**Comment by kgamecarter** [comment]
mfd format is same to bin. Just difference file extension name.
I think just remove the menu item.
Or implement change file name?

**Comment by iceman1001** [comment]
remove in  "convert to..." 
but keep for open file..
