### ISSUE TITLE
Templates for toy-to-life tokens

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#44]
The data mapping of several toy-to-life tokens like  _Disney Infinity, Skylanders, Amiboo, Lego Dimension_ etc etc would be excellent to have color templates of.  

Thats why I ask the community for help.   A template file is extremly simple to do.

**Sample**
https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/master/ChameleonMiniGUI/Templates/Ultralight-EV1-164B.txt

**Color names**
http://www.flounder.com/csharp_color_table.htm

**Comment by kevin2008-01** [comment]
.Cyan Disney Infinity   Right, ? you need table?

**Comment by iceman1001** [comment]
I would need a template file,   I have no time to make these files myself but I do have all data mapping from these different toys-to-life,   thanks for the suggestion.

**Comment by kevin2008-01** [comment]
send the correct format you need for working. when i have moment i work for community.

**Comment by kevin2008-01** [comment]
create only one sample you need iceman1001

**Comment by iceman1001** [comment]
The sample file is quite easy to understand.

Byte offset; length; text color ; background color; description 

The colors uses the known names, see the link in first post. 

There is already some template files, they make a great starting point. 
Just add it to the template folder and you will be able to test it on a dump file direct

**Comment by hiwanz** [comment]
<img width="611" alt="untitled" src="https://user-images.githubusercontent.com/338102/45256809-5ece1880-b3ce-11e8-87aa-2c1887bb9e16.png">

I've add a new series templates, you will see it in next release or you can build it from the source by yourself.

**Comment by iceman1001** [comment]
Yes,  good work,  this issue is about a specific subset of templates.

**Comment by iceman1001** [comment]
@bogiton   https://twitter.com/kaitai_io/status/1107011025222750208
Look at that fancy visualisation...  that would have been cool to have

**Comment by bogiton** [comment]
Wow, yeah, this is cool! How could we integrate something like that? Create a logical tree structure of each data section?

**Comment by iceman1001** [comment]
We don't need a structure to start with.  Keep it simlpe.   Like the template has rows,   we would just print those but when click on one, it would highlight the selected bytes :)

**Comment by iceman1001** [comment]
Since no-one is working on this,  I will close it... 
Maybe @McEloff  has the energy to add it?
