### ISSUE TITLE
emulate mifare classic with 7bit UID... possible ?

### ISSUE THREAD

**Issue by Shashadow** [iceman1001/ChameleonMini-rebootedGUI#47]
Hello,

I just have a little question about GUI for Chameleon, I have one from Lab401.
It seems possible to emulate mifare classic 1k or 4k with 7bit UID in the description, but after some research, I don't found any way to emulate a mifare with 7bit UID card.

just 4bit is ok.
I read datasheet for 7bit, It seem all is in block 0, but I'm Don't Believe we can change bit of UID just with mofify data … ? no ?

So is it possible to emulate a 7bit mifare classic (1k or 4k) as we can do it for 4bit ?
thanks

Regards
David

**Comment by iceman1001** [comment]
it is possible but I don't think its implemented in current firmware.

Feel free to add it,  I think in the offical revG firmware there is some support for it.
