### ISSUE TITLE
Converting function in UcExplorer

### ISSUE THREAD

**Issue by hiwanz** [iceman1001/ChameleonMini-rebootedGUI#59]
Is "To Bin" the same with "To MFD", or is "To bin" means "to mfd binary", I didn't see the implement of "To MFD" menu item in UcExplorer.cs
```csharp
var emllabel = new ToolStripMenuItem { Text = "To EML" };
var binlabel = new ToolStripMenuItem { Text = "To BIN" };
var mfdlabel = new ToolStripMenuItem { Text = "To MFD" };
```

[https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/f43d4bbd5cc3da06764d8882bbfd5dd9d9b40fcf/ChameleonMiniGUI/UcExplorer.cs#L281](https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/f43d4bbd5cc3da06764d8882bbfd5dd9d9b40fcf/ChameleonMiniGUI/UcExplorer.cs#L281)

```csharp
switch (to)
{
    case ConvertFileEnum.Eml:
    {
        ...
    }
    case ConvertFileEnum.Bin:
    {
        ...
    }
}           
```

[https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/f43d4bbd5cc3da06764d8882bbfd5dd9d9b40fcf/ChameleonMiniGUI/UcExplorer.cs#L301](https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/f43d4bbd5cc3da06764d8882bbfd5dd9d9b40fcf/ChameleonMiniGUI/UcExplorer.cs#L301)

**Comment by hiwanz** [comment]
According to [http://nfc-tools.org/index.php/Libnfc:nfc-mfclassic](http://nfc-tools.org/index.php/Libnfc:nfc-mfclassic), **MFD stands for MIFARE dump file**, the "Interpretation" section has explained the structure of .mfd file, which is totally the same with the .bin file, so "To MFD" could be removed, could I?

**Comment by hiwanz** [comment]
OK. I'll deal with it, see it in next PR

**Comment by bogiton** [comment]
I think that the difference between MFD and BIN is that the first one represents a binary dump in "Chameleon" format (tag sectors first and extra info afterwards), while the BIN is the binary dump that comes from Proxmark (first the extra information and then the actual tag bytes).

**Comment by iceman1001** [comment]
well.  it depends..  
binary pm3 files for MFU (ultralight etc) is different,    Dumps from mifare classic is just a memory dump binary.   The question is when is MFD format used?   only for mifare classic dumps?
Do MFD have extra info in it?

**Comment by iceman1001** [comment]
..one of these days a json format should emerge...
