### ISSUE TITLE
new release v1.0

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#6]
And here I open up for the first release of the Rebooted GUI.

It should be working with **both** old rebooted firmware  **Chameleon-new-1.0**  and the updated firmware from here [ChameleonMini Rebooted](https://github.com/iceman1001/ChameleonMini-rebooted)

**Comment by iceman1001** [comment]
We see a time when old and new GUI will work together, but in the long run, the old one will disappear since the firmware here has fixes and enhancments and those will break functionality with old GUI.

So,
old gui + old fw  = ok
old gui + new fw = ok
new gui + old fw = ok
new gui + new fw = ok

---We will try to have backwardsfunctionality with old firmware.  Its easy to detect what it can do, and we can compensate for it in the GUI..
meaning the following should apply for a long time.
new gui + old fw = ok
new gui + new fw = ok

**Comment by iceman1001** [comment]
@bogiton  I did a click-once deployment.   So, if you are fine with current version of the GUI,  we might aswell create this release :)

**Comment by bogiton** [comment]
Cool stuff this click-once deployment!
I was thinking that maybe we should wait a couple of days to see if any bug/problem come out and then go forward with the release! :)

**Comment by iceman1001** [comment]
yeah, I did some minor fixes in the looping. 
Changing the mfkey at the moment to use parallell instead,  got stuck with progressbar reporting..

The default timeout should also be a settings / appconfig value.

**Comment by bogiton** [comment]
Parallel as in async? Yeah, I just remembered the unknown Calculation_times() function in the sample gui code you provided, which was used for the progress division.
Or we could just say something like for the timeout: "If not set, default interval is 2sec".

**Comment by iceman1001** [comment]
@bogiton  you can proof-read the draft?  If ok,  we publish it.

**Comment by bogiton** [comment]
Go for it :)

**Comment by iceman1001** [comment]
v1.0 is released :)
https://github.com/iceman1001/ChameleonMini-rebootedGUI/releases
