### ISSUE TITLE
Increase Performance of SendCommand

### ISSUE THREAD

**Issue by Vrumfondel** [iceman1001/ChameleonMini-rebootedGUI#64]
Current implementation with waiting static 100ms for a response from Chameleon is slowing down especially the startup of the tool.
Proposal:
After sending Command, wait for response until timeout occurs.

**Comment by iceman1001** [comment]
100ms is slowing down?   1/10 of a second... hm..  you must be in a hurry

**Comment by Vrumfondel** [comment]
Well,
during startup I counted 128 calls to SendCommand, that's allready 12.8 seconds.
That's what I would call "long" for a program to silently startup ....

The difference is really noticable ...
