### ISSUE TITLE
todo: Add support for new json dump format 

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#67]
**Todo**
Add support for new json dump format just introduced in proxmark3 RRG repo.

**Comment by kgamecarter** [comment]
Is there a plan to use the [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json)?

**Comment by iceman1001** [comment]
Dunno which json implementation yet,  but there are minimalistic fast ones.

**Comment by kgamecarter** [comment]
Consider DataContractJsonSerializer. It's not fastest one, but built-in .NET Framework.
Is there a JSON sample file?

**Comment by iceman1001** [comment]
..I haven't actually tested the new dump format,   so hold on....

And here it is,  
https://pastebin.com/x6Xwc1EW

**Comment by iceman1001** [comment]
fastJSON is one that I have used earlier but it always comes down to how to read nodes inside it in a nice easy way...

**Comment by bogiton** [comment]
Hmm, sector keys are saved in the dump? Until now, for the RevE we only save the blocks of the tag.

**Comment by iceman1001** [comment]
yeah,  I see it as optional.  the data part is most important.

**Comment by iceman1001** [comment]
we add the keys in the sector trailer as in pm3 binaries or eml.   You can still do that,  but we also extract them in json.

**Comment by kgamecarter** [comment]
I finished upload json dump.

Hexbox needs to be implemented ApplyChange.
Also need to write back to the sector trailer?

**Comment by iceman1001** [comment]
Sadly you will have to rebase it ...  I merged the old PR...

**Comment by iceman1001** [comment]
Not sure with the hexboxes,   I will need to see your code first...

**Comment by kgamecarter** [comment]
Here is upload dump https://github.com/kgamecarter/ChameleonMini-rebootedGUI/commit/384e13f0daf155d75849409feeb847cf6602052c

**Comment by iceman1001** [comment]
Cool,   yeah  matching the sectorkeys would be nice...
and reading of EML files aswell..

**Comment by iceman1001** [comment]
The JSON addition seem to work.  I can drag and drop a json file onto the dump management tab and it loads.  When saving the json swapps a bit around the different parts,  so that can be confusing the first time.  However the change in block data is correct so far.  Also sector keys is updated when a Sector trailer is modified.  How cool is that!  :)

**Comment by iceman1001** [comment]
ok,   [DataMember(Order=1)]  sorted those things out.   The outcome json file is identical as PM3 style.  :)

**Comment by iceman1001** [comment]
Now its the upload/download..   I noticed the download tried to save it as 4k

**Comment by iceman1001** [comment]
it should but the  RevE/RevG PR  messed up the load of tag slot settings for RevE  (which I am testing with)..
So för RevE the GUI doesn't work right now :(

**Comment by iceman1001** [comment]
the 4K format has a different sized sectors,  which isn't dealt with in current solution.

**Comment by kgamecarter** [comment]
Yes, i need the 4k json sample

**Comment by iceman1001** [comment]
no,   no Mifare Ultralight / NTAG json exists yet.

**Comment by kgamecarter** [comment]
I tried to make 4k json.
please check 32~39 sectorkeys are right format.
https://pastebin.com/wdRZ7KiX

**Comment by RfidResearchGroup** [comment]
The csave should be able to do 4k.  I just dont have access to a gen1a 4k card right now.
