### ISSUE TITLE
Not connecting to Chameleon any more

### ISSUE THREAD

**Issue by Vrumfondel** [iceman1001/ChameleonMini-rebootedGUI#73]
Somthing got broken in establishing the connection;
On 1st look it seems the GUI tries to connect to the first available COM-Port, no matter what this is ..

**Comment by iceman1001** [comment]
Not really,  it will try getting which serial ports is available,  then it tries to identify if the current port has a vid/pid connected to a chameleon.   if not, then loop to next available serial port. 
See method  https://github.com/iceman1001/ChameleonMini-rebootedGUI/blob/master/ChameleonMiniGUI/FrmMain.cs#L1207

**Comment by Vrumfondel** [comment]
Im currently debugging this.
Currently it seems pb_device.Image doesn't like to load warning.ico ....

**Comment by iceman1001** [comment]
Bugger,    We need a image for  "Unknown device" ...   Can't show RevE or RevG....

**Comment by Vrumfondel** [comment]
No question about having a seperate image there, I just say that the current image-type seems to be the wrong one ...

**Comment by Vrumfondel** [comment]
Confirmed: An icon can not be casted into an bitmap ....
Converting the .ico to an png and using this as ressource works again ...

**Comment by iceman1001** [comment]
PR?

**Comment by Vrumfondel** [comment]
Will come in ~ 2hrs ...
