### ISSUE TITLE
download dump file too big 64kb

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#8]
I tested to upload a tagdump which worked nice,  then I tried to download it and compare it with my original dump file.
All well, but the dump file is 64kb large.  Not at all the 1kb which I was expecting.

Something in the xmodem received function is bad

**Comment by iceman1001** [comment]
Aha,  well.. maybe its in the firmware..

The download of dumps is done via xmodem and  this function inside  memory.c  MemoryDownloadBlock( buffer, blockaddress, bytecount)

It uses the define MEMORY_SIZE_PER_SETTING as bound to how much to send...

**Comment by bogiton** [comment]
Another solution would be to limit the number of bytes that the GUI receives/sends by first querying the current MEMSIZE of the selected slot.

**Comment by iceman1001** [comment]
yup. go for that solution :)

**Comment by bogiton** [comment]
Done. Not very optimal, but it works.

**Comment by iceman1001** [comment]
what to do?  At least we have something that works on offical revg,  offical rebooted and iceman rebooted.  Who can complain about that?  First get it to work,  then make it nicer.
