### ISSUE TITLE
Unhandled exceptions when building in for x64 target

### ISSUE THREAD

**Issue by Vrumfondel** [iceman1001/ChameleonMini-rebootedGUI#83]
When building for x64, during startup the app gets stuck due to some unhandled exceptions.
Should be remove x64 as a target, or fix the problem ?

**Comment by iceman1001** [comment]
fix problem if doable

**Comment by iceman1001** [comment]
still unhandled exceptions?

**Comment by Vrumfondel** [comment]
Hm, strange enough I can't reproduce this any more. I'll close it for now.
