### ISSUE TITLE
SaveActiveSlot() saving wrong value

### ISSUE THREAD

**Issue by Vrumfondel** [iceman1001/ChameleonMini-rebootedGUI#84]
Moving this to a own function is a good idea, but current implementation is wrong:
Doing a slotindex++ in SaveActiveSlot() is only working for RevE, since _tagslotIndexOffset is 1.
For RevG the offset is 0, so there is 1 added when saving, but not substracted when restoring --> Marked slot is one index to high ....

I will fix this in my next PR

**Comment by iceman1001** [comment]
looking forward to the PR

**Comment by iceman1001** [comment]
Yeah,   move to operations tag and show result in output window,   and become disabled on RevE rebooted firmware..

**Comment by iceman1001** [comment]
So I moved it and resized the utils controls.  Looks better.
Now there is some translations missing because of new GUI
