### ISSUE TITLE
draft v1.2 release

### ISSUE THREAD

**Issue by iceman1001** [iceman1001/ChameleonMini-rebootedGUI#87]
@kgamecarter    
@Vrumfondel 
@bogiton 

I published a v1.2.0.5 for those who use the click-once deployment. 
Also added a new branch in preperation for a new release.

would need some proper tests of  RevG functionality.   I have tested on my RevE rebooted.  It works as expected.

Is there any of the issuses still there,   (see issues and projects tabs)  which you guys maybe wanna fix?

Great work!

**Comment by iceman1001** [comment]
and yeah,  we need to update the pictures in the readme.md...    They really are missing stuff :)

**Comment by iceman1001** [comment]
Cool,  MCT dump format supported done!   Thanks to @kgamecarter !

**Comment by bogiton** [comment]
You guys are on fire! I press the refresh button and I see tons of fixed/added stuff each day!
Very good job!

**Comment by iceman1001** [comment]
The love feels soo good here.  The GUI gets some well deserved love!    Dropping bin/json/eml/mct files and the dump management tab just takes it  :)    Feels so good!

**Comment by iceman1001** [comment]
Pushed out the v1.2.0.5  as click-once deployment.

**Comment by iceman1001** [comment]
OK,  if you all test it out.  I belive the new dump formats works nice.  
Some more color templates would be nice to have. 

Latest click-once deployment is  v1.2.0.7

**Comment by iceman1001** [comment]
Alrighty then.    added a new iClass template and fixed the template control to fill out the size.   Looks good now.

Latest click-once deployment is v1.2.0.8

**Comment by iceman1001** [comment]
How is the RevG testing going?   I looked at RevG firmware,  they really uped the game.  Its looks great.  RevE rebooted is behind.

**Comment by iceman1001** [comment]
And yeah,  rumours :)   There may be a RevG rebooted device.  What more should it have inside?

**Comment by Vrumfondel** [comment]
I don't see any issues with RevG so far ...

**Comment by iceman1001** [comment]
There is a lot of more commands in RevG firmware.

There some minor stuff under project 'enhance gui' but I like this GUI now.   Great addons!

**Comment by iceman1001** [comment]
so since nobody has ideas or suggestions,  I think I will close this issue and release  V1.2   

@bogiton   do you wanna edit the draft release (its there already)

**Comment by bogiton** [comment]
Seems perfect :)
